# Generated by Django 2.2.7 on 2019-11-25 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstancePizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Пиццы в заказ',
                'verbose_name': 'Пицца в заказ',
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
            ],
            options={
                'verbose_name_plural': 'Пиццы',
                'verbose_name': 'Пицца',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('pizzas', models.ManyToManyField(blank=True, null=True, to='pizzas.InstancePizza')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Заказы',
                'verbose_name': 'Заказ',
            },
        ),
        migrations.AddField(
            model_name='instancepizza',
            name='pizza_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pizza_template', to='pizzas.Pizza'),
        ),
    ]
