# Generated by Django 2.2.6 on 2019-12-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='description',
            field=models.CharField(default='Some description', max_length=555),
        ),
        migrations.AddField(
            model_name='pizza',
            name='photo',
            field=models.ImageField(default='static/pizzas/no_photo.png', height_field=720, upload_to='static/pizzas/', width_field=720),
        ),
    ]
