# Generated by Django 2.2.6 on 2019-12-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_auto_20191212_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='photo',
            field=models.ImageField(default='pizzas/no_photo.png', upload_to='pizzas/'),
        ),
    ]
