# Generated by Django 2.2.6 on 2019-12-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_auto_20191212_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='photo',
            field=models.ImageField(default='static/pizzas/no_photo.png', upload_to='static/pizzas/'),
        ),
    ]
