# Generated by Django 2.2.6 on 2019-12-16 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_auto_20191212_1520'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
